# Install the pre-commit hooks below with
# 'pre-commit install'

# Auto-update the version of the hooks with
# 'pre-commit autoupdate'

# Run the hooks on all files with
# 'pre-commit run --all'

# `^` is used to match the start of the file name
# `.*` is used to match any number of characters
# `$` is used to match the end of the file name


repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-json
        files: .*\.json$

      - id: pretty-format-json
        files: .*\.json$

      - id: check-yaml
      - id: check-toml
      - id: trailing-whitespace
        types: [python]
        exclude: .*\.ipynb$  # to avoid upcomming problems

      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-added-large-files
        args: ['--maxkb=5000']
      - id: detect-private-key


  # check the validity of docker files
  - repo: https://github.com/iamthefij/docker-pre-commit
    rev: v3.0.1
    hooks:
      - id: docker-compose-check

  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
      - id: dockerfilelint


  # strip jupyter outputs if the notebook is not in "notebooks" folder
  # Note that the "notebooks" folder is ignored in ".gitignore"
  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
        exclude: .*/notebooks/.*\.ipynb



  - repo: https://github.com/mwouts/jupytext
    rev: v1.16.1
    hooks:
      - id: jupytext
        language: python
        entry: jupytext --sync --set-formats "notebooks//ipynb,scripts//py:light" **/notebooks/*.ipynb
        require_serial: true
        types_or: [jupyter, python]
        # files: .*/notebooks/.*\.ipynb
        # args: [--sync]

  # create .py in "_notebooks" folder for ONLY .ipynb files that are in "notebooks" folder
  # https://stackoverflow.com/questions/69909719/jupytext-pre-commit-config-when-notebooks-are-ignored-in-git
  #     always_run: true  # if true, this hook will run even if there are no matching files.
  #     pass_filenames: false
  #     require_serial: true  #  if true, this hook will execute using a single process instead of in parallel.

  # - repo: https://github.com/mwouts/jupytext
  #   rev: v1.16.1
  #   hooks:
  #     - id: jupytext
  #       language: python
  #       entry: jupytext --pre-commit-mode --set-formats "notebooks//ipynb,scripts//py:light"
  #       require_serial: true
  #       types_or: [jupyter, python]
  #       files: .*/notebooks/.*\.ipynb
  #       args: [--sync]


  # very fast linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.7
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [ "--fix", "--show-fixes" ]  #  --exit-non-zero-on-fix
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]
